drop user manager;
create user manager@localhost
	identified by '123';
GRANT CREATE SESSION, CREATE TABLE, CREATE PROCEDURE
    , CREATE SEQUENCE, CREATE TRIGGER, CREATE VIEW
    , CREATE SYNONYM, ALTER SESSION, CREATE ANY INDEX, CREATE PUBLIC SYNONYM
TO manager;